# Generated by Django 2.1.3 on 2018-11-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('modified_header', models.CharField(max_length=127, null=True)),
                ('etag_header', models.CharField(max_length=127, null=True)),
                ('news_feed_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsfeed.NewsFeed')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(db_index=True, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
