# Generated by Django 2.1.3 on 2018-11-03 18:26

from django.db import migrations
from django.db.migrations import RunPython

URLS = [
    'https://www.nba.com/rss/nba_rss.xml',
    'https://www.nba.com/rss/highlights.rss',
    'http://www.espn.com/espn/rss/nba/news',  # this one does not seem to support https
    'https://www.rotoworld.com/rss/feed.aspx?sport=nba&ftype=article&count=12&format=rss',
    'https://www.rotoworld.com/rss/feed.aspx?sport=nba&ftype=news&count=12&format=rss'
]


def load_urls(apps, schema_editor):
    NewsFeedURL = apps.get_model('newsfeed', 'NewsFeedURL')
    for url in URLS:
        NewsFeedURL.objects.create(url=url)


def clear_urls(apps, schema_editor):
    NewsFeedURL = apps.get_model('newsfeed', 'NewsFeedURL')
    NewsFeedURL.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        RunPython(load_urls, clear_urls)
    ]
