# Generated by Django 2.1.3 on 2018-11-03 18:26

from django.db import migrations
from django.db.migrations import RunPython

URLS = [
    'https://www.nba.com/rss/nba_rss.xml',
    'https://www.nba.com/rss/highlights.rss',
    'http://www.espn.com/espn/rss/nba/news',  # this one does not seem to support https
    'https://www.rotoworld.com/rss/feed.aspx?sport=nba&ftype=article&count=12&format=rss',
    'https://www.rotoworld.com/rss/feed.aspx?sport=nba&ftype=news&count=12&format=rss'
]


def load_urls(apps, schema_editor):
    NewsFeedURL = apps.get_model('newsfeed', 'NewsFeedURL')
    for url in URLS:
        NewsFeedURL.objects.create(url=url)

    NBATeam = apps.get_model('nba_profile', 'NBATeam')
    for team in NBATeam.objects.all().exclude(code='mavericks'):
        # for some reason the Mavericks feed doesn't follow the same format as the others
        NewsFeedURL.objects.create(url=f'https://www.nba.com/{team.code}/rss.xml')

    NewsFeedURL.objects.create(url='https://www.mavs.com/feed/')


def clear_urls(apps, schema_editor):
    NewsFeedURL = apps.get_model('newsfeed', 'NewsFeedURL')
    NewsFeedURL.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
        ('nba_profile', '0002_base_player_data')
    ]

    operations = [
        RunPython(load_urls, clear_urls)
    ]
