# Generated by Django 2.1.3 on 2018-12-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_load_newsfeed_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.TextField(),
        ),
    ]
