# Generated by Django 2.1.2 on 2018-10-31 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('jersey', models.PositiveSmallIntegerField(null=True)),
                ('is_active', models.BooleanField()),
                ('position', models.CharField(max_length=32)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='height in meters')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='weight in kilograms')),
                ('birth_date', models.DateField(null=True, verbose_name='UTC birth date')),
                ('nba_debut_year', models.PositiveSmallIntegerField(null=True)),
                ('college_name', models.CharField(max_length=128, null=True)),
                ('last_affiliation', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('city', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('abbr', models.CharField(max_length=4)),
                ('conference', models.CharField(max_length=32)),
                ('division', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('min_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nba_profile.NBATeam', to_field='nba_id'),
        ),
    ]
