# Generated by Django 2.1.2 on 2018-11-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_profile', '0003_userteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userteam',
            old_name='user_id',
            new_name='user',
        ),
    ]
