# Generated by Django 2.1.3 on 2018-11-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_profile', '0008_playergamestats_teamgamestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_num', models.IntegerField()),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='nba_profile.NBAGame')),
            ],
        ),
    ]
