# Generated by Django 2.1.3 on 2018-11-28 17:12

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('nba_profile', '0010_auto_20181128_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='time_played',
            field=models.DurationField(default=timedelta(0)),
            preserve_default=False,
        ),
    ]
