# Generated by Django 2.1.3 on 2018-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_profile', '0011_playergamestats_time_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbagame',
            name='season',
            field=models.IntegerField(default=2018),
        ),
    ]
